### ISSUE TITLE
Develop way to export validation results

### ISSUE THREAD

**Issue by fontanka16** [frozen-solid/CSharp_MARC#12]
Hi!
I cannot export the validation results from the grid. I would like to export the results in a structured way that enables me to further analyze the validation results in other tools.

**Comment by fontanka16** [comment]
I think I could solve it myself if you could point me in the right direction.

**Comment by frozen-solid** [comment]
That's a great idea. I'll look into incorporating it into the next release of the application.

**Comment by fontanka16** [comment]
Great. In the end, I was able to get it out through the database, but i think it would be make a usable addition to the project.
